[package]
name = "nsfw-core"
edition.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
http = { workspace = true }
utoipa = "5"

[dev-dependencies]
rstest = { workspace = true }
